[package]
name = "pickle"
version = "0.1.0"
authors = ["zhangzheng1"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde-pickle = "0.6.1"
